<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Wesley Stone">
<meta name="dcterms.date" content="2026-09-07">
<meta name="description" content="A three-statement model, a DCF and a comparables analysis, built to test whether the biggest interstate migration flow in the country actually reaches a builder’s margin. It doesn’t, and not because of interest rates but supply elasticity.">

<title>Why North Carolina’s Migration Boom Isn’t Making Homebuilders Money – Wesley Stone</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2d0a04b3c53b956175a65d37aae98281.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Wesley Stone</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../gallery.html"> 
<span class="menu-text">Photography</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#the-call" id="toc-the-call" class="nav-link active" data-scroll-target="#the-call">The call</a></li>
  <li><a href="#demand-is-real-margin-is-the-problem" id="toc-demand-is-real-margin-is-the-problem" class="nav-link" data-scroll-target="#demand-is-real-margin-is-the-problem">Demand is real; margin is the problem</a></li>
  <li><a href="#the-forecast" id="toc-the-forecast" class="nav-link" data-scroll-target="#the-forecast">The forecast</a></li>
  <li><a href="#valuation" id="toc-valuation" class="nav-link" data-scroll-target="#valuation">Valuation</a></li>
  <li><a href="#the-bear-case" id="toc-the-bear-case" class="nav-link" data-scroll-target="#the-bear-case">The bear case</a></li>
  <li><a href="#sources-and-limitations" id="toc-sources-and-limitations" class="nav-link" data-scroll-target="#sources-and-limitations">Sources and limitations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why North Carolina’s Migration Boom Isn’t Making Homebuilders Money</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Economics</div>
    <div class="quarto-category">Finance</div>
    <div class="quarto-category">Housing</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>A three-statement model, a DCF and a comparables analysis, built to test whether the biggest interstate migration flow in the country actually reaches a builder’s margin. It doesn’t, and not because of interest rates but supply elasticity.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Wesley Stone </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ratings">
<div class="rating">
<span class="k">Rating</span><span class="v">Neutral</span>
</div>
<div>
<span class="k">Target</span><span class="v">$160</span>
</div>
<div>
<span class="k">Price</span><span class="v">$140.07</span>
</div>
<div>
<span class="k">Return</span><span class="v">+14%</span>
</div>
<div>
<span class="k">Mkt cap</span><span class="v">$3.5bn</span>
</div>
<div>
<span class="k">Bull / bear</span><span class="v">199 / 100</span>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong><a href="MHO_coverage_note.pdf">→ Download the note as a PDF</a></strong> · <a href="MHO_model.xlsx">download the model (Excel)</a></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>UPDATE (9/11)</strong> I noticed today that MHO’s price had fallen significantly from when I first posted this, and I found a couple minor errors in the model which had lowered the target, so I updated the call to Neutral from Underweight. I feel somewhat vindicated for the original rating, though the current movement may just be short-term noise.</p>
</div>
</div>
</div>
<p>I just moved to North Carolina for my graduate education. I’m not alone: in the year to July 2025 North Carolina gained a net 84,000 residents from other states, more than any other state. Given my previous work in housing, I was curious whether this presented an opportunity for homebuilders, and investors, to capitalize on new demand. I identified M/I Homes as a mid-cap builder with a large enough presence in the region for the influx of new arrivals to move the needle.</p>
<section id="the-call" class="level2">
<h2 class="anchored" data-anchor-id="the-call">The call</h2>
<p>I am initiating on M/I Homes at <strong>Neutral</strong> with a <strong>$160 price target</strong>, +14% against the current price and slightly below the street. I set ratings against the cost of equity rather than against zero because a stock expected to return less than the return its risk demands is one to hold below benchmark weight, whatever the sign of the number. On that basis +14% against a 12.0% cost of equity is a paltry +2.2 points of alpha. MHO pays no dividend, so that’s all you get. Hardly exciting, and not riskless either. My bull case, at $199, requires two independent things to go right at once, rates falling and Sunbelt supply clearing, whereas the bear, at $100 needs only one thing to keep happening.</p>
<p>M/I Homes is a well-run company: net cash, retiring roughly 5% of its shares a year, and at 1.10× book not obviously expensive. The problem is what it now earns on that book. Return on equity has fallen from 19.2% in 2024 to 9.3% on trailing numbers. At a 12.0% cost of equity, today’s multiple already pays for a normalized return of about 12.9%. My base case reaches 9.8% by 2028, and only by assuming a competitive recovery I can’t verify.</p>
<p>The more interesting finding is underneath the rating, and it’s the opposite of what I expected. In 2025 the <span class="s-tag">Southern</span> segment, Raleigh and Charlotte alongside Florida and Texas, saw its operating margin fall from 18.1% to 10.4%. The <span class="n-tag">Northern</span> segment, the Midwest business the market treats as a legacy drag, held at 14.7%. The growth region stopped carrying the profit.</p>
</section>
<section id="demand-is-real-margin-is-the-problem" class="level2">
<h2 class="anchored" data-anchor-id="demand-is-real-margin-is-the-problem">Demand is real; margin is the problem</h2>
<p>That net inflow is real, but it is slowing. 2025 was about 81% of the 2020–21 peak, and more importantly, arrivals are not clearing at the price builders want. House price indices for Raleigh and Charlotte rose just 1.1% and 1.5% over the year to Q2 2026, against 3.8% inflation: roughly 2.6% and 2.3% declines in real terms, in the state everyone is moving to.</p>
<p>This wasn’t a rate shock. The 30-year fixed mortgage fell from 6.72% in 2024 to 6.59% in 2025 while the <span class="s-tag">Southern</span> margin was collapsing. <span class="s-tag">Southern</span> cost per home barely moved. Essentially the whole margin decline was price handed back at the closing table.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-margin" class="quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-margin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-margin-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-margin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Segment operating margin. Northern has been flat for two years; Southern lost nearly 800bp in one. My base case does not restore Southern to its 2024 level within the forecast. Source: FY2025 10-K segment note; estimates my own.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Splitting the <span class="s-tag">Southern</span> segment into price and cost settles the question. Cost per home, adjusted for the $41m of <span class="s-tag">Southern</span> inventory write-offs taken in 2025, went from $358k to $360k over two years. Average selling price fell more than $26k. There is no cost story here.</p>
<div class="cell">
<div id="tbl-unit" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Unit economics by region, $ thousands per home delivered, excluding write-offs
</figcaption>
<div aria-describedby="tbl-unit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 36%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">2023A</th>
<th style="text-align: right;">2024A</th>
<th style="text-align: right;">2025A</th>
<th style="text-align: right;">2026E</th>
<th style="text-align: right;">2027E</th>
<th style="text-align: right;">2028E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Southern</td>
<td style="text-align: left;">Net average selling price</td>
<td style="text-align: right;">485.4</td>
<td style="text-align: right;">478.6</td>
<td style="text-align: right;">459.2</td>
<td style="text-align: right;">441.8</td>
<td style="text-align: right;">447.7</td>
<td style="text-align: right;">458.8</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Cost per home</td>
<td style="text-align: right;">358.4</td>
<td style="text-align: right;">351.1</td>
<td style="text-align: right;">360.3</td>
<td style="text-align: right;">359.2</td>
<td style="text-align: right;">366.4</td>
<td style="text-align: right;">374.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Gross profit per home</td>
<td style="text-align: right;">127.0</td>
<td style="text-align: right;">127.5</td>
<td style="text-align: right;">98.9</td>
<td style="text-align: right;">82.6</td>
<td style="text-align: right;">81.3</td>
<td style="text-align: right;">84.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Gross margin</td>
<td style="text-align: right;">26.2%</td>
<td style="text-align: right;">26.6%</td>
<td style="text-align: right;">21.5%</td>
<td style="text-align: right;">18.7%</td>
<td style="text-align: right;">18.2%</td>
<td style="text-align: right;">18.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Northern</td>
<td style="text-align: left;">Net average selling price</td>
<td style="text-align: right;">478.1</td>
<td style="text-align: right;">489.4</td>
<td style="text-align: right;">507.1</td>
<td style="text-align: right;">500.7</td>
<td style="text-align: right;">511.4</td>
<td style="text-align: right;">524.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Cost per home</td>
<td style="text-align: right;">385.4</td>
<td style="text-align: right;">381.4</td>
<td style="text-align: right;">394.0</td>
<td style="text-align: right;">394.0</td>
<td style="text-align: right;">402.6</td>
<td style="text-align: right;">412.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Gross profit per home</td>
<td style="text-align: right;">92.7</td>
<td style="text-align: right;">108.0</td>
<td style="text-align: right;">113.1</td>
<td style="text-align: right;">106.7</td>
<td style="text-align: right;">108.7</td>
<td style="text-align: right;">111.9</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Gross margin</td>
<td style="text-align: right;">19.4%</td>
<td style="text-align: right;">22.1%</td>
<td style="text-align: right;">22.3%</td>
<td style="text-align: right;">21.3%</td>
<td style="text-align: right;">21.3%</td>
<td style="text-align: right;">21.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This was an important lesson for me, because I came into this project with the assumptions of the Portland, OR housing market in place. But the Southeast generally has much laxer zoning and permitting codes than the West Coast, which allows the market to quickly respond to the influx of demand with more construction, apparently even to the point of oversaturation. From a policy perspective it’s a success story, but unfortunately MHO wasn’t positioned to profit from that success.</p>
</section>
<section id="the-forecast" class="level2">
<h2 class="anchored" data-anchor-id="the-forecast">The forecast</h2>
<p>Revenue is built region by region, deliveries times average selling price for <span class="n-tag">Northern</span> and <span class="s-tag">Southern</span> separately, rather than off a blended growth rate, because I’m interested in regional trends. Gross margin is what is left after an incentive load reduces the realized price and a separately-driven cost per home is subtracted. Incentive load is a base rate, plus a slope against the mortgage rate above a 5.5% neutral level, plus an explicit competition premium to account for the Southern margin collapse.</p>
<p>The 2026 estimate is set against reported first-half results: 4,120 deliveries, $5.57 of EPS, a 459k average price. My full year of $11.98 implies 4,432 second-half deliveries, 7.6% above the first half, against an actual 6.3% step in 2025. On earnings the comparison is less flattering, implying $6.41 of second-half EPS against $5.57 in the first, whereas 2025’s second half fell 24% sequentially. What makes me comfortable is the year-over-year line rather than the sequential one: $6.41 in 2H 2026 is essentially flat against the $6.34 actually earned in 2H 2025.</p>
<div class="cell">
<div id="tbl-sens" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: 2027E diluted EPS: mortgage rate (rows) against Southern competition premium (columns)
</figcaption>
<div aria-describedby="tbl-sens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">0.5pp</th>
<th style="text-align: right;">1.7pp</th>
<th style="text-align: right;">3.0pp</th>
<th style="text-align: right;">4.2pp</th>
<th style="text-align: right;">5.5pp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5.50%</td>
<td style="text-align: right;">17.13</td>
<td style="text-align: right;">16.29</td>
<td style="text-align: right;">15.39</td>
<td style="text-align: right;">14.53</td>
<td style="text-align: right;">13.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">6.00%</td>
<td style="text-align: right;">16.46</td>
<td style="text-align: right;">15.61</td>
<td style="text-align: right;">14.72</td>
<td style="text-align: right;">13.85</td>
<td style="text-align: right;">12.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6.35%</td>
<td style="text-align: right;">15.99</td>
<td style="text-align: right;">15.14</td>
<td style="text-align: right;">14.25</td>
<td style="text-align: right;">13.38</td>
<td style="text-align: right;">12.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">6.75%</td>
<td style="text-align: right;">15.45</td>
<td style="text-align: right;">14.60</td>
<td style="text-align: right;">13.71</td>
<td style="text-align: right;">12.85</td>
<td style="text-align: right;">11.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7.25%</td>
<td style="text-align: right;">14.78</td>
<td style="text-align: right;">13.93</td>
<td style="text-align: right;">13.04</td>
<td style="text-align: right;">12.17</td>
<td style="text-align: right;">11.26</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Read that grid across, not down. Moving the mortgage rate over its whole range shifts 2027 EPS by about $2.35. Moving the competition premium over its range shifts it by $3.52. The competitive variable matters more than the Fed, which is the opposite of how this sector is usually discussed.</p>
<section id="against-the-consensus" class="level3">
<h3 class="anchored" data-anchor-id="against-the-consensus">Against the consensus</h3>
<p>M/I Homes publishes no quantitative guidance; no delivery, revenue, margin or EPS target appears in either the FY2025 or the Q2 2026 release. Every forecast here is mine. Consensus is the one external check available, but it is thin. 7 analysts have published a rating in the past twelve months, 4 positive, 2 hold and 1 sell, but only one price target has been issued in the past three months, and the EPS estimates below carry a stamp of 24 June 2026. The most recent rating action is a Zacks Research downgrade on 9 September 2026.</p>
<div class="cell">
<div id="tbl-cons" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cons-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: My estimates against consensus
</figcaption>
<div aria-describedby="tbl-cons-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Mine</th>
<th style="text-align: right;">Consensus</th>
<th style="text-align: right;">Range</th>
<th style="text-align: right;">As of</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2026E revenue</td>
<td style="text-align: right;">$4.13bn</td>
<td style="text-align: right;">$4.18bn</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">24 Jun 2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">2026E EPS</td>
<td style="text-align: right;">$11.98</td>
<td style="text-align: right;">$12.19</td>
<td style="text-align: right;">$11.43–$13.25</td>
<td style="text-align: right;">24 Jun 2026</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2027E EPS</td>
<td style="text-align: right;">$13.15</td>
<td style="text-align: right;">$14.08</td>
<td style="text-align: right;">not published</td>
<td style="text-align: right;">24 Jun 2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Price target</td>
<td style="text-align: right;">$160</td>
<td style="text-align: right;">$164.25</td>
<td style="text-align: right;">$155.00–$172.00</td>
<td style="text-align: right;">11 Sep 2026</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rating</td>
<td style="text-align: right;">Neutral</td>
<td style="text-align: right;">Moderate Buy</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">11 Sep 2026</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>I sit slightly below the street on both years and on the target: 2% on 2026, 7% on 2027 and 3% on the target. My 2026 number sits inside the published range. I do assume that the 2024-5 drop was a bit anomalous, so the competition premium decaying boosts the numbers, but this is partially offset by baking in the current high mortgage rates, which if anything seems a bit conservative based off current trends. I’m comfortable with a minor deviation from the conventional wisdom because seven ratings is not that many, and I feel confident about the assumptions in my model. But Neutral really isn’t a crazy hot take here.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Composition of the recovery.</strong> Of the $1.17 of 2027 EPS growth over 2026, $0.90 is extrapolation of reported trends: volume, price, cost and the buyback. The mortgage-rate path accounts for $-0.36. And $0.64 is the <span class="s-tag">Southern</span> competition premium decaying.</p>
</div>
</div>
</div>
</section>
</section>
<section id="valuation" class="level2">
<h2 class="anchored" data-anchor-id="valuation">Valuation</h2>
<p>I ran a DCF and a comparables analysis separately, and they disagree sharply. The DCF, at a 10.81% WACC and 2.5% terminal growth, gives $120.79 as of today, well below the market. The unadjusted peer median price-to-book of 1.46× gives about $198, significantly above it. Because the price target is a twelve-month one, Table 5 carries the DCF value rolled forward a year at the 12.0% cost of equity, or $135, and the comparables leg is likewise struck on book at roughly September 2027 rather than book today. Both legs are therefore quoted at the same future date as the target.</p>
<p>One caveat: 78% of the enterprise value in that DCF is terminal value. That’s high because a builder reinvests so heavily in land and work in progress that little cash reaches shareholders inside the forecast window, which pushes the weight of the answer onto the perpetual assumption. It is a reason to treat the DCF as a discipline rather than a measurement, and it is why I do not weight it higher than 60%.</p>
<p>The DCF is low because a builder’s earnings recovery does not reach shareholders. My base case grows NOPAT from $300m in 2026 to $400m in 2030, but land and homes under construction absorb roughly $200m a year over the same period. Growth, for a builder, consumes cash.</p>
<div class="cell">
<div id="tbl-peers" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-peers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: The comparable set. Prices at the close of 11 September 2026; equity from each company’s most recent 10-Q; trailing net income derived from market capitalisation and trailing P/E so every company sits on the same basis.
</figcaption>
<div aria-describedby="tbl-peers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Company</th>
<th style="text-align: right;">Price</th>
<th style="text-align: right;">Mkt cap $m</th>
<th style="text-align: right;">P/B</th>
<th style="text-align: right;">P/E</th>
<th style="text-align: right;">ROE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DHI — D.R. Horton</td>
<td style="text-align: right;">$137.89</td>
<td style="text-align: right;">38,570</td>
<td style="text-align: right;">1.62×</td>
<td style="text-align: right;">13.12×</td>
<td style="text-align: right;">12.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEN — Lennar</td>
<td style="text-align: right;">$79.60</td>
<td style="text-align: right;">19,180</td>
<td style="text-align: right;">0.89×</td>
<td style="text-align: right;">12.37×</td>
<td style="text-align: right;">7.2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PHM — PulteGroup</td>
<td style="text-align: right;">$117.85</td>
<td style="text-align: right;">22,170</td>
<td style="text-align: right;">1.70×</td>
<td style="text-align: right;">12.06×</td>
<td style="text-align: right;">14.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">TOL — Toll Brothers</td>
<td style="text-align: right;">$134.92</td>
<td style="text-align: right;">12,430</td>
<td style="text-align: right;">1.46×</td>
<td style="text-align: right;">10.81×</td>
<td style="text-align: right;">13.5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MTH — Meritage</td>
<td style="text-align: right;">$64.22</td>
<td style="text-align: right;">4,190</td>
<td style="text-align: right;">0.83×</td>
<td style="text-align: right;">13.39×</td>
<td style="text-align: right;">6.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MHO — M/I Homes</td>
<td style="text-align: right;">$140.07</td>
<td style="text-align: right;">3,540</td>
<td style="text-align: right;">1.10×</td>
<td style="text-align: right;">11.78×</td>
<td style="text-align: right;">9.3%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The striking thing in that table is the dispersion. Earnings multiples sit in a pretty narrow band, 10.81× to 13.39×, while returns on equity run from 6.2% to 14.1%. So the market is paying similar earnings multiples for notably different returns on capital.</p>
<div class="cell">
<div id="tbl-val" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Valuation summary: two independent views
</figcaption>
<div aria-describedby="tbl-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 68%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Value</th>
<th style="text-align: right;">vs price</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Discounted cash flow, rolled forward 12 months</td>
<td style="text-align: right;">$135</td>
<td style="text-align: right;">-4%</td>
<td style="text-align: right;">60%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peer median P/B on Sep-2027E book</td>
<td style="text-align: right;">$198</td>
<td style="text-align: right;">+41%</td>
<td style="text-align: right;">40%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weighted price target</td>
<td style="text-align: right;">$160</td>
<td style="text-align: right;">+14%</td>
<td style="text-align: right;">100%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>There’s a $63 a share difference between the two methods, which makes me tread cautiously both with how I weight them and how much stock I put in the headline number. The DCF is grounded in what the business earns and what that leaves for shareholders once land has absorbed its share, while the comparables are grounded in what the market currently pays other builders for a dollar of book, and say nothing about whether the cash ever arrives. I weight the first more heavily for that reason.</p>
<p>However, it’s ultimately a judgment call, and due to the wide gap the target is more sensitive to it than I would like. At an even split it is about $166, while weighting the comparables two-to-one over the DCF reaches roughly $177. Weighting the comparables at 100% gives $198, which is a solid Buy, so an analyst who trusts peer multiples and distrusts my cash-flow forecast reaches a quite different conclusion from the same data. My objection is that most of that number is a re-rating rather than earnings. Of the $58 by which the comparables value exceeds today’s price, only about $9 comes from book value growing between now and September 2027. The remaining $49 assumes M/I Homes is awarded the peer multiple of 1.46× book instead of the 1.10× it trades on today. That is the whole bet, and I’m skeptical that a builder earning 9.8% on equity should be priced like ones earning 12% to 14%.</p>
</section>
<section id="the-bear-case" class="level2">
<h2 class="anchored" data-anchor-id="the-bear-case">The bear case</h2>
<p>The bear case isn’t so much a recession as that the competition premium is structural rather than cyclical. It could be that even the slow decay in my base case is too generous, and the discounting simply persists.</p>
<p>Affordability in Raleigh and Charlotte is now binding, so the marginal buyer can only be reached by moving down in price and specification. Every builder in those markets faces the same arithmetic and reaches the same conclusion at the same time. MHO controls 30,863 lots in the <span class="s-tag">Southern</span> region, 18,124 of them owned outright. Land bought for a $500k product and sold into a $440k market does not earn a 20% margin, and the $41m of <span class="s-tag">Southern</span> write-offs in 2025 may be the first installment rather than the last.</p>
<p>The rate backdrop doesn’t help. The 30-year fixed mortgage has risen from a 5.98% trough this year to 6.76% at 10 September, with the 30-year Treasury at 5.37%. I do not forecast rates: I hold the mortgage rate at today’s level for the whole forecast, so nothing in the target depends on a rate view. If rates ratchet higher still and <span class="s-tag">Southern</span> incentives follow, return on equity settles near 6.2%. The bull case rests on Sunbelt spec inventory clearing faster than I assume, and gets return on equity to 12.1%. I value both the same two ways as the base case, so the numbers are comparable rather than a separate judgement call.</p>
<div class="cell">
<div id="tbl-scen" class="cell quarto-float quarto-figure quarto-figure-left anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Scenarios, valued the same two ways as the base case
</figcaption>
<div aria-describedby="tbl-scen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: right;">2027E EPS</th>
<th style="text-align: right;">2028E ROE</th>
<th style="text-align: right;">P/B used</th>
<th style="text-align: right;">Value</th>
<th style="text-align: right;">vs price</th>
<th style="text-align: left;">Multiple taken from</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bull</td>
<td style="text-align: right;">$15.83</td>
<td style="text-align: right;">12.1%</td>
<td style="text-align: right;">1.62×</td>
<td style="text-align: right;">$199</td>
<td style="text-align: right;">+42%</td>
<td style="text-align: left;">D.R. Horton, which earns 12.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Base</td>
<td style="text-align: right;">$13.15</td>
<td style="text-align: right;">9.8%</td>
<td style="text-align: right;">1.46×</td>
<td style="text-align: right;">$160</td>
<td style="text-align: right;">+14%</td>
<td style="text-align: left;">the peer median</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bear</td>
<td style="text-align: right;">$9.18</td>
<td style="text-align: right;">6.2%</td>
<td style="text-align: right;">0.83×</td>
<td style="text-align: right;">$100</td>
<td style="text-align: right;">-28%</td>
<td style="text-align: left;">Meritage, which earns 6.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>What I find reassuring about this is that neither end of the range is an extrapolation into empty space. Each scenario maps onto a builder that exists today. The bear case has MHO earning 6.2% on equity, close to the 6.2% Meritage earns now, and Meritage trades at 0.83× book. The bull case has it earning 12.1%, close to D.R. Horton’s 12.3%, and D.R. Horton trades at 1.62× book. The base case sits between the two and takes the peer median rather than any single builder’s multiple. So the question is not whether these multiples are achievable in the abstract; it is which of these real companies M/I Homes comes to resemble. That is a more concrete question than a range of price targets usually implies, and it’s why I am comfortable with the spread being wide.</p>
<p>The bull case is modestly higher return than the bear: +42% against -28%. However, the bull rests on rates easing and Sunbelt supply clearing, whereas the bear simply needs the competition premium not to decay. The base case is a lackluster, though positive, return. MHO is not an especially attractive stock, even with the recent drop, but it’s no longer clearly overpriced. I see it as solidly Neutral.</p>
<p>What would change my mind, constructively: two consecutive quarters of <span class="s-tag">Southern</span> gross margin expansion with average selling price stable or rising. Negatively: further write-offs in the <span class="s-tag">Southern</span> land bank, or <span class="s-tag">Southern</span> average selling price falling below $430k.</p>
</section>
<section id="sources-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="sources-and-limitations">Sources and limitations</h2>
<p>Claude Code assisted me with gathering data, writing code and Excel. Financial statements were copied from the FY2025 Form 10-K (filed 13 February 2026); segment revenue, cost and operating income come from its Note 12. Operating detail by region comes from the Q4 earnings releases for 2023, 2024 and 2025 and the Q2 2026 release. Consolidated figures were checked against SEC XBRL company facts and match to the dollar. Rates and house price indices are from FRED; prices and trailing multiples from stockanalysis.com; ratings from marketbeat.com at the close of 11 September 2026. All forecasts are mine.</p>
<p>Two limitations are worth stating. MHO reports only two geographic segments, so Raleigh and Charlotte cannot be separated from Florida and Texas in public filings. “Southern” is the closest available proxy for the North Carolina question. And the financial services segment, about 11% of segment operating income, is valued inside the consolidated DCF rather than separately, which is a simplification rather than a strictly correct treatment.</p>
<p><em>Prepared as a personal analytical exercise, not investment advice. No position held.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>