---
title: "2024 Election Model"
author: "Wesley Stone"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readxl)
library(sf)
```

```{r}
pop <- read_excel("NST-EST2023-POP.xlsx")
area <- read_csv("state-areas.csv")
```

```{r}
names(pop) <- c("state", "base", 2020, 2021, 2022, 2023)
cleanpop <- pop %>% 
  slice(9:59) %>% 
  select(state, `2023`)

cleanpop$state <- sub("^\\.", "", cleanpop$state)

names(area) <- c("state", "area")
statedensity <- cleanpop %>% 
  left_join(area, by="state") %>% 
  mutate(density = 2023/area) %>% 
  mutate(density_adjusted = log(density))

statedensity %>%
  filter(state != "District of Columbia") %>% 
  ggplot(aes(x = state, y = density_adjusted)) +
  geom_point()
```

```{r}
urban <- read_csv("urbanization-index-2022.csv")
```

```{r}
state_urban <- urban %>% 
  group_by(state) %>% 
  summarize(urbanindex = mean(urbanindex))
```

```{r}
state_abbrs <- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")

cleanpop2 <- cleanpop %>% 
  filter(state != "District of Columbia") %>% 
  mutate(new = state_abbrs) %>% 
  mutate(pop_prop = `2023`/334235500)

names(cleanpop2) <- c("old", "pop_total", "state", "pop_prop")

urban_table <- state_urban %>% 
  left_join(cleanpop2, by = "state") %>% 
  mutate(urban_prop = pop_prop * urbanindex)

preds <- urban_table %>% 
  mutate(urbanlean = urbanindex - 11.19338) %>% 
  mutate(predlean = urbanlean * 12) %>% 
  select(state, predlean)

preds %>%
  mutate(predoutcome = predlean + 3) %>% 
  arrange(state)
```

